# Generated by Django 5.0.3 on 2024-03-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Licence',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='cat',
            new_name='licence',
        ),
    ]
