# Generated by Django 5.0.3 on 2024-04-08 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_category_options_card_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.category'),
        ),
    ]
