# Generated by Django 5.0.3 on 2024-05-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_staffcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcard',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
