# Generated by Django 5.0.3 on 2024-05-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_staffcard_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='department',
        ),
        migrations.DeleteModel(
            name='StaffCard',
        ),
    ]
