# Generated by Django 5.0.3 on 2024-03-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='no_plate',
            field=models.CharField(blank=True, max_length=100, verbose_name='number plate'),
        ),
    ]
