# Generated by Django 5.0.3 on 2024-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_sticker_no_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='expires',
            field=models.DateField(null=True),
        ),
    ]
