# Generated by Django 5.0.3 on 2024-03-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_clerk_alter_user_is_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
