# Generated by Django 5.0.3 on 2024-06-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(default='sales', max_length=255),
        ),
    ]
