# Generated by Django 5.0.3 on 2024-05-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='knowledgebasecategory',
            options={'verbose_name_plural': 'Knowledge Base Categories'},
        ),
    ]
