# Generated by Django 5.0.3 on 2024-03-12 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_info', models.CharField(max_length=100, verbose_name='Warranty')),
                ('computer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='system_audit/')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['computer_name'],
            },
        ),
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('processor', models.CharField(blank=True, help_text='In GHz(e.g.:i5 2.9 GHz)', max_length=100, null=True)),
                ('ram', models.IntegerField(help_text='In GB', verbose_name='RAM')),
                ('hdd', models.IntegerField(help_text='In GB', verbose_name='HDD/Storage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComputerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MicrosoftOfficeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['model__name'],
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComputerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assets.computer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='assets.computermodel'),
        ),
        migrations.AddField(
            model_name='computermodel',
            name='computer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.computertype'),
        ),
        migrations.AddField(
            model_name='computer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_locations', to='assets.location'),
        ),
        migrations.AddField(
            model_name='computermodel',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.maker'),
        ),
        migrations.CreateModel(
            name='MicrosoftOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(max_length=30, unique=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_installed', models.BooleanField(default=False)),
                ('has_failed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(blank=True, help_text='serial number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_installations', to='assets.computer')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assets.microsoftofficeversion')),
            ],
            options={
                'ordering': ['-date_installed'],
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor',
            field=models.ManyToManyField(blank=True, related_name='monitors', to='assets.monitor'),
        ),
        migrations.CreateModel(
            name='MonitorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='monitor_models/')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.maker')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='monitor',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='assets.monitormodel'),
        ),
        migrations.AddField(
            model_name='computer',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.operatingsystem', verbose_name='Operating System'),
        ),
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='printer_models/')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.maker')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='assets.project'),
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('printer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_locations', to='assets.location')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='assets.printermodel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.status')),
            ],
            options={
                'ordering': ['ip_addr'],
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.status'),
        ),
    ]
