# Generated by Django 5.0.3 on 2024-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_computer_deleted_at_computer_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftoffice',
            name='date_installed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
