# Generated by Django 5.0.3 on 2024-05-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_computer_options_alter_computer_computer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
