# Generated by Django 5.0.3 on 2024-05-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_computer_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='is_new',
        ),
    ]
