# Generated by Django 5.0.3 on 2024-06-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_printersupply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printersupply',
            options={'verbose_name_plural': 'printer supplies'},
        ),
    ]
