# Generated by Django 5.0.3 on 2024-06-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_printersupply_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='printersupply',
            name='min_count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='printersupply',
            name='part_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
