# Generated by Django 5.0.3 on 2024-06-20 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_printersupply_printer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printersupply',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='assets.printer'),
        ),
    ]
