# Generated by Django 5.0.3 on 2024-06-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_alter_printersupply_supplier'),
        ('suppliers', '0002_alter_supplier_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printersupply',
            name='supplier',
            field=models.ManyToManyField(to='suppliers.supplier'),
        ),
    ]
