# Generated by Django 5.0.3 on 2024-06-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_alter_printersupply_supplier'),
        ('suppliers', '0002_alter_supplier_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printersupply',
            name='min_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='printersupply',
            name='supplier',
            field=models.ManyToManyField(blank=True, to='suppliers.supplier'),
        ),
    ]
