# Generated by Django 5.0.3 on 2024-06-21 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0001_initial'),
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printermodel',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='makers.maker'),
        ),
    ]
