# Generated by Django 5.0.3 on 2024-06-21 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('printers', '0003_printer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_departments', to='departments.department'),
        ),
    ]
