# Generated by Django 5.0.3 on 2024-06-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_printer_department'),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statuses.status'),
        ),
    ]
