# Generated by Django 5.0.3 on 2024-03-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options_alter_ticket_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_by',
        ),
    ]
