# Generated by Django 5.0.3 on 2024-03-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_comment_updated_by_remove_ticket_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
    ]
