# Generated by Django 5.0.3 on 2024-03-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
