# Generated by Django 5.0.3 on 2024-03-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
