# Generated by Django 5.0.3 on 2024-05-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_options_alter_ticket_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-is_closed', 'updated_at']},
        ),
    ]
