# Generated by Django 5.0.3 on 2024-05-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-updated_at']},
        ),
    ]
