# Generated by Django 5.0.3 on 2024-05-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-ticket_status__name', '-updated_at']},
        ),
    ]
