# Generated by Django 5.0.3 on 2024-06-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['is_closed', '-updated_at']},
        ),
    ]
